Todo_project/Todo_project/urls.py
from django.contrib import admin
from django.urls import path
from ToDo_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home, name="home"),
    path("delete<int:id>", views.delete, name="delete"),
    path("update<int:id>", views.update, name="update"),
    path("signup", views.signup, name="signup"),
    path("login", views.login_f, name="login"),
    path("logout", views.logout_f, name="logout"),




]

Todo_project/ToDo_app/models.py
from django.db import models

# Create your models here.

class Todo_model(models.Model):
    item = models.CharField(max_length=255)
    time  = models.DateTimeField(auto_now_add=True)
    

Todo_project/ToDo_app/forms.py
from django import forms
from .models import Todo_model

class Todo_form(forms.ModelForm):
    class Meta:
        model = Todo_model
        fields = "__all__"
        

Todo_project/ToDo_app/views.py
from django.shortcuts import render,redirect
from ToDo_app.models import Todo_model
from .forms import Todo_form
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
# Create your views here.
@never_cache
@login_required(login_url="login")
def home(request):
    if request.method =="GET":
        form = Todo_form()
        data = Todo_model.objects.all()
        return render(request,"home.html",{'data':data,'form':form})
    else:
        form = Todo_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    return render(request,"home.html")

@never_cache
@login_required(login_url="login")
def delete(request,id):
    try:
        data = Todo_model.objects.get(id=id)
        data.delete()
        return redirect("home")
    except Exception as e:
        print(e)
        return render(request,"home.html")

def update(request,id):
    data = Todo_model.objects.get(id=id)
    if request.method =="GET":
        form = Todo_form(instance=data)
        data = Todo_model.objects.all()
        return render(request,"home.html",{'data':data,'form':form})
    else:
        form = Todo_form(request.POST,instance=data)
        if form.is_valid():
            form.save()
            return redirect("/")
    return render(request,"home.html")

    
def login_f(request):
    if request.method =="POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect("home")
        else:
            messages.error(request,"Username/Password is Wrong")
            return redirect("login")


    return render(request,'login.html')

def logout_f(request):
    logout(request)
    return redirect("login")



def signup(request):
    if request.method =="POST":
        username = request.POST['username']
        password = request.POST['password']
        email=request.POST['email']
        cpassword = request.POST['cpassword']

        if password == cpassword:
            if User.objects.filter(email=email).exists():
                 messages.error(request,"Email Allready Exists ")
                 return redirect("signup")
            
            elif  User.objects.filter(username=username).exists():
                messages.error(request,"User Allready Exists ")
                return redirect("signup")
            
            else:
                user = User.objects.create_user(username=username,password=password,email=email)
                return redirect("login")
        else:
             messages.error(request,"Password Does Not match")
             return redirect("signup")


    return render(request,'signup.html')

Todo_project/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">ToDo List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        
       <li class="nav-item">
          <a class="nav-link btn btn-outline-danger" href="{% url 'logout' %}">Logout</a>
        </li>

      </ul>
      {{user}}
      {% else %}
      
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        {% endif %}
      
    </div>
  </div>
</nav>
  </header>
  <main>
{% block content %}
{% endblock %}
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

Todo_project/templates/home.html
{% include 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}


<style>
    input#id_item {
    width: 35%;
    display: table;
    margin: auto;
}
</style>
<div class="container text-center">
    <h1>ADD Task HERE</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type="submit" class="btn btn-success" >Add Task</button>
    </form>
    {% if data %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Sr.</th>
                <th>Task</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr>
                <td>{{i.id}}</td>
                <td>{{i.item}}</td>
                <td><a href="{% url 'delete' i.id %}" class="btn btn-danger">Delete</a></td>
                <td><a href="{% url 'update' i.id %}" class="btn btn-danger">Edit</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    
    
    
    <br>

</div>

<script>
    document.getElementsByClassName('requiredField').style.display = 'none'
</script>



{% else %}
No Item Till Now
{% endif %}

{% endblock %}

Todo_project/templates/login.html
{% include 'base.html' %}
{% block content %}
<title>Login</title>
<div class="container">
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Username</label>
        <input type="text"  class="form-control" name="username" required>

        <label for="">Password</label>
        <input type="password" class="form-control"  name="password" required>
        <br>
        <button type="submit" class="btn btn-success">Login</button> or <a href="/signup"> Create Account</a>
    </form>
</div>

{% if messages %}
{% for i in messages %}
<script>
    alert('{{i}}')
</script>
{% endfor %}
{% endif %}
{% endblock %}

Todo_project/templates/signup.html
{% include 'base.html' %}
{% block content %}
<div class="container">
    <h1>Signup</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Username</label>
        <input type="text" name="username" class="form-control" required>

        <label for="">Email</label>        
        <input type="text" name="email" class="form-control" required>
        
        <label for="">Password</label>
        <input type="text" name="password" class="form-control" required>

        <label for="">Confirm Password</label>
       <input type="text" name="cpassword" class="form-control" required>
        <br>
        <button type="submit" class="btn btn-success">Signup</button>  
    </form>
</div>
{% if messages %}
{% for i in messages %}
<script>
    alert('{{i}}')
</script>
{% endfor %}
{% endif %}
{% endblock %}